config-version: "2.6.1"

messages:
  commands_no_perm: "&cYou don't have permission to use this command."
  no_permissions: "&cYou don't have permission to use this KillEffect."
  effect_set: "&aYou have selected the KillEffect: &e%effect%"
  effect_already_set: "&eYou have already selected this KillEffect!"
  config_reloaded: "&aConfiguration successfully reloaded!"
  gui_title: "&6Select your KillEffect"
  effect_not_found: "&cKillEffect not found!"
  miss_usage: "&cUse this command &e/kt reload|set|test"
  only_players: "&cOnly players can execute this command!"
  effect_executed: "&aKillEffect executed: &e%effect%"
  invalid_potion: "&cInvalid or missing configured potion: no potion applied."
  potion_set: "&aYou received: &e%potion% %amplifier%"
  not_enough_coins: "&cYou don't have enough KillCoins to buy this effect."
  purchase_failed: "&cAn error occurred while purchasing the effect."
  purchase_success: "&aYou successfully purchased the effect &e%effect%&a!"
  already_bought: "&aAlready purchased"
  price_format: "&6Price: &e%price% %currency%"
  killcoins_only_players: "&cOnly players can use /kt killcoins bal without specifying a player."
  killcoins_balance_self: "&aYour KillCoins balance is: &e%balance%%currency%"
  killcoins_balance_other: "&aThe KillCoins balance of &e%player% &ais: &e%balance%%currency%"
  killcoins_balance_usage: "&cUsage: /kt killcoins bal [player]"
  killcoins_reset: "&aThe balance of &e%player% &ahas been reset to &e%balance%%currency%"
  killcoins_reset_usage: "&cUsage: /kt killcoins reset <player>"
  killcoins_invalid_amount: "&cInvalid amount: &e%amount%"
  killcoins_add: "&aYou added &e%amount%%currency% &ato &e%player%"
  killcoins_take: "&aYou removed &e%amount%%currency% &afrom &e%player%"
  killcoins_take_not_enough: "&c%player% does not have enough %currency%"
  killcoins_set: "&aThe balance of &e%player% &ahas been set to &e%amount%%currency%"
  kill_reward: "&a+%amount% %currency% &7(Kill reward)"
  killcoins_usage: "&eCorrect usage:\n&e /kt killcoins add <player> <amount>\n&e /kt killcoins take <player> <amount>\n&e /kt killcoins set <player> <amount>\n&e /kt killcoins reset <player>\n&e /kt killcoins bal [player]\n"
  cooldown_active: "&cWait %delay% seconds before using your KillEffect again!"
  on_command_cooldown: "&cPlease wait %seconds%s before using this command again."
  effect_removed: "&aYou deactivated the current Kill Effect."
  effect_none_selected: "&7No effect is currently selected."

server-info: false

auto-update:
  enabled: true

management-structure:
  review-command:
    enabled: true
  test_command:
    cooldown:
      enabled: true
      delay: 10 #In seconds
  players:
    enabled: true #For disable/active killeffect for players
    cooldown:
      enabled: false
      delay: 5 #In seconds
  mobs:
    enabled: true #For disable/active killeffect for mobs
    cooldown:
      enabled: true
      delay: 20 #In seconds

economy:
  enabled: true #If disabled check the permission for the effects
  use_internal: true # If true use internal economy (killcoins) else use external eco like essentials etc.
  starting-balance: 10 #After reset the user coins
  reward:
    enabled: true
    settings:
      player_kill: 10
      mob_kill: 1
  currency:
    singular: "KillCoin"
    plural: "KillCoins"
    symbol: "KC"

resource_pack:
  updates:
    url: "url update, move it to settings to enable it ---> https://download.mc-packs.net/pack/d2435c3e646fabd12461269d5138cc17e9f964ed.zip <--- url update, move it to settings to enable it"
    sha1: "sha1 update, move it to settings to enable it ---> d2435c3e646fabd12461269d5138cc17e9f964ed <--- sha1 update, move it to settings to enable it"
  settings:
    enabled: true
    url: "https://download.mc-packs.net/pack/d5889f788003340479e3f767852eddee152ee544.zip"
    sha1: "d5889f788003340479e3f767852eddee152ee544"
    uuid: "1d216c05-b1c2-48ee-aff5-4a6c823b463a"
    required: true
    prompt: "This resource pack is required to play."
  sounds:
    bow-hit:
      name: "kt.hs1"
    aura-farm:
      name: "kt.aurab"

gui:
  none: "&7None"
  buttons:
    close: "&c✖ Close"
    current_effect: "&eCurrent Effect: %effect%"
    disable: "&4➤ Disable Effect"
    currency: "&7Your balance: &a%bal% %bal_symbol%"

events:
  enabled: true
  broadcast:
    players: "&e%killer% &akilled &b%deaded%&a and his luck started the &6lucky event &e%event%&a, go to his location to get the rewards too, it ends in: &e%end%"
    finish_collected: "&aAll the money has been collected"
    finish_not_collected: "&aThe event is ended"
    money_pickup: "&aYou have collected money, %remaining% pieces are missing"
  list:
    money_fountain:
      enabled: true
      chance: 5
      settings:
        drop: 64
        material: EMERALD
        money_value: 20
        duration: 90

    meteor_shower:
      enabled: true
      chance: 2
      settings:
        meteor_count: 15
        material: DIAMOND
        money_value: 50
        duration: 40


effects:
  firephoenix:
    enabled: true
    name: "&cFirePhoenix"
    description: "&cBurn &7your enemies with &6firephoenix"
    price: 1500
    projectiles:
      enabled: true
      settings:
        damage: true
        rage: 200
        delay: 3
        value: 4
    damage:
      enabled: true
      value: 2
      radius: 3

  lightning:
    enabled: true
    name: "&eLightning"
    description: "&bSummon a &elightning bolt &bon your target"
    price: 2500
    damage:
      enabled: true
      value: 5
      radius: 4

  explosion:
    enabled: true
    name: "&4Explosion"
    description: "&4Boom! &7A visual explosion effect"
    price: 3000
    projectiles:
      damage: true
      settings:
        rage: 5
        value: 4
    damage:
      enabled: true
      value: 5
      radius: 5

  hearts:
    enabled: true
    name: "&dHearts"
    description: "&dLove hearts &7when you kill"
    price: 2000
    damage:
      enabled: false
      value: 0
      radius: 0

  notes:
    enabled: true
    name: "&aNotes"
    description: "&aMusical effect &ein the rhythm of death"
    price: 1800
    damage:
      enabled: false
      value: 0
      radius: 0

  cloud:
    enabled: true
    name: "&fCloud"
    description: "&fMysterious &7and haunting fog"
    price: 2200
    damage:
      enabled: true
      value: 1
      radius: 3

  smoke:
    enabled: true
    name: "&8Smoke"
    description: "&8Smoke &7and shadows in the air"
    price: 2100
    damage:
      enabled: true
      value: 2
      radius: 3

  totem:
    enabled: true
    name: "&6Totem"
    description: "&6Epic &eparticles &6of the totem"
    price: 4000
    damage:
      enabled: true
      value: 4
      radius: 5

  end:
    enabled: true
    name: "&5End"
    description: "&5Creepy &dEnderman &5effect"
    price: 3500
    damage:
      enabled: true
      value: 4
      radius: 6

  pigstep:
    enabled: true
    name: "&dPigStep"
    description: "&dPig &bStep &eeffect"
    price: 2750
    damage:
      enabled: false
      value: 0
      radius: 0

  shockwawe:
    enabled: true
    name: "&ashockwawe"
    description: "&aSoul fly up and down"
    price: 700
    effectexplosion:
      enabled: true
      type: BLINDNESS
      amplifier: 1
      duration: 3
    damage:
      enabled: true
      value: 1
      radius: 7

  skeleton:
    enabled: true
    name: "&fSkeleton"
    description: "&fThe victim into a skeleton"
    price: 1000

  warden:
    enabled: true
    name: "&3Warden"
    description: "&3Warden &eeffect"
    price: 7045
    damage:
      enabled: true
      value: 7
      radius: 6

  glowmissile:
    enabled: true
    name: "&bGlowMissile"
    description: "&bGlow missile &7effect"
    price: 5300
    damage:
      enabled: true
      value: 8
      radius: 5

  grave:
    enabled: true
    name: "&8Grave"
    description: "&fPlace a cross for the victim."
    price: 1000

  sniper:
    enabled: true
    name: "&cSniper"
    description:
      - "&7Long Mortal Shot"
      - "&8Only kill with bow"
    price: 4250
    damage:
      enabled: true
      value: 5
      radius: 8

  enchantcolumn:
    enabled: true
    name: "&rEnchant&7Column"
    description: "&rEnchant&7Column &eExplosion!"
    price: 6000
    effectexplosion:
      type: REGENERATION
      amplifier: 2
      duration: 10
    damage:
      enabled: true
      value: 10
      radius: 10

  fireworks:
    enabled: true
    name: "&bFireworks"
    description: "&cFire &fworks &7and explosions"
    structure: true
    price: 6345
    damage:
      enabled: true
      value: 6
      radius: 9

  wither:
    enabled: true
    name: "&0Wither"
    description: "&0Wither &8and &fflash"
    price: 10500
    damage:
      enabled: true
      value: 7
      radius: 4

  stellarcollapse:
    enabled: true
    name: "&eStellar Collapse"
    description: "&cmini-supernova &ecollapse"
    price: 7000
    damage:
      enabled: true
      value: 2
      radius: 3

  dimensionalrift:
    enabled: true
    name: "&dDimensional &bRift"
    description: "&4Glitched &ddimensional brift"
    price: 8250
    damage:
      enabled: true
      value: 6
      radius: 7

  cryocore:
    enabled: true
    name: "&bCryo &9Core"
    description: "&9Cryo snow &bcore"
    structure: true
    price: 6250
    duration-multiplier: 1
    damage:
      enabled: true
      value: 1
      radius: 16

  aurafarming:
    enabled: true
    name: "&5Aura Farming"
    description: "&5Aura Farming &8- &dDestroy players by destroying their aura"
    price: 25000
    aura-settings:
      boost-perks:
        damage:
          amplifier: 2
          duration: 20
        potion:
          type: REGENERATION
          amplifier: 2
          duration: 10
        damage-message: "&b☄ You received a damage boost for {duration}s!"
        potion-message: "&d✨ You received {potion} {amplifier} for {duration}s!"
    damage:
      enabled: true
      value: 10
      radius: 20
    push-settings:
      enabled: true
      damage-per-seconds: 2

  mace:
    enabled: true
    name: "&cMa&6ce"
    description: "&5Destroy your enemy with &bMACE"
    price: 11250
    damage:
      enabled: true
      value: 5
      radius: 16