name: KT
version: '${project.version}'
main: com.monkey.kt.KT
author: MonkeyMoon104
api-version: '1.13'
depend:
  - LuckPerms
  - WorldGuard
  - PlaceholderAPI
softdepend:
  - ViaVersion
  - ViaRewind
  - ViaBackwards
  - Vault

commands:
  killeffect:
    description: Open the KillEffect GUI
    aliases: [kt]

permissions:
  kt.admin.bypass:
    description: Allows players to bypass colodwns and effects disabled
    default: op
  kt.killcoins.add:
    description: Allows use of /kt killcoins add
    default: op
  kt.killcoins.take:
    description: Allows use of /kt killcoins take
    default: op
  kt.killcoins.set:
    description: Allows use of /kt killcoins set
    default: op
  kt.killcoins.reset:
    description: Allows use of /kt killcoins reset
    default: op
  kt.killcoins.bal:
    description: Allows use of /kt killcoins bal
    default: true

  kt.reload:
    description: Allows reloading the plugin configuration
    default: op

  kt.set:
    description: Allows set effect without GUI
    default: op

  kt.test:
    description: Allows test the plugin effects
    default: op

  kt.admin.suggestion:
    description: Allows player send suggestion directly to plugin owner
    default: op

  kt.user.review:
    description: Allows player send review directly to plugin owner
    default: true

  kt.firephoenix.use:
    description: Use the fire kill effect
    default: op

  kt.lightning.use:
    description: Use the lightning kill effect
    default: op

  kt.explosion.use:
    description: Use the explosion kill effect
    default: op

  kt.hearts.use:
    description: Use the hearts kill effect
    default: op

  kt.notes.use:
    description: Use the notes kill effect
    default: op

  kt.cloud.use:
    description: Use the cloud kill effect
    default: op

  kt.smoke.use:
    description: Use the smoke kill effect
    default: op

  kt.totem.use:
    description: Use the totem kill effect
    default: op

  kt.end.use:
    description: Use the end kill effect
    default: op

  kt.pigstep.use:
    description: Use the pigstep kill effect
    default: op

  kt.shockwawe.use:
    description: Use the shockwawe kill effect
    default: op

  kt.skeleton.use:
    description: Use the skeleton kill effect
    default: op

  kt.warden.use:
    description: Use the warden kill effect
    default: op

  kt.glowmissile.use:
    description: Use the glowmissile kill effect
    default: op

  kt.grave.use:
    description: Use the grave kill effect
    default: op

  kt.sniper.use:
    description: Use the sniper kill effect
    default: op

  kt.enchantcolumn.use:
    description: Use the enchantcolumn kill effect
    default: op

  kt.fireworks.use:
    description: Use the fireworks kill effect
    default: op

  kt.wither.use:
    description: Use the wither kill effect
    default: op

  kt.stellarcollapse.use:
    description: Use the stellar collapse kill effect
    default: op

  kt.dimensionalrift.use:
    description: Use the dimensional rift kill effect
    default: op

  kt.cryocore.use:
    description: Use the cryo core kill effect
    default: op

  kt.aurafarming.use:
    description: Use the aura farming kill effect
    default: op

  kt.mace.use:
    description: Use the mace kill effect
    default: op
